### 登录获取 token
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

### 带 token 添加学生
POST http://localhost:8080/students
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3ODI0NTc1NjMsImV4cCI6MTc4MjU0Mzk2M30.UN9p3SVt6SpPGKg8IfDM4vYXez2VJTccxxWdYRjlM9E

{
  "id": "200",
  "name": "创建人测试",
  "age": 20,
  "score": 88
}

### 查询学生
GET http://localhost:8080/students/200
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3ODI0NTc1NjMsImV4cCI6MTc4MjU0Mzk2M30.UN9p3SVt6SpPGKg8IfDM4vYXez2VJTccxxWdYRjlM9E

